#!/bin/bash

./configure --disable-system --enable-linux-user --enable-guest-base --disable-gtk --disable-sdl --disable-vnc --target-list=i386-linux-user --enable-debug --disable-werror --extra-cflags='-DAFL -DDOUBLE_EMPTY_EXIT_BY_DEFAULT -g3 -ggdb -gdwarf-4'
