#!/bin/bash

./configure --disable-system --enable-linux-user --enable-guest-base --disable-gtk --disable-sdl --disable-vnc --target-list=i386-linux-user --enable-debug --disable-werror --extra-cflags='-DDEBUG_LENIENT_LENGTHS -DDEBUG_SIGNAL -DDEBUG_TB_CHECK -DDEBUG_TB_INVALIDATE -g3 -ggdb -gdwarf-4'
